default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 'sanngatuusagi0088'
  host: localhost

development:
  <<: *default
  database: asagao_dev

test:
  <<: *default
  database: asagao_test

production:
  adapter: postgresql
  host: ec2-54-163-245-3.compute-1.amazonaws.com
  username: zwaerpbeopebil
  password: sU6Mr9MomYJP2X66F9EfjykZrl
  database: dfb2lqn024jor9
